# Generated by Django 5.0.6 on 2024-07-06 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_book_optional_publisher_country_alter_member_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="num_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer", models.EmailField(max_length=254)),
                ("rating", models.PositiveIntegerField()),
                ("comments", models.TextField(blank=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.book"
                    ),
                ),
            ],
        ),
    ]
