# Generated by Django 5.0.6 on 2024-07-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_book_optional_publisher_country_alter_member_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="num_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
